- src/ellipsis.bash
- src/git.bash
- src/pkg.bash
- test/ellipsis.bats
> Support branch installs.

- src/ellipsis.bash
Allows the user to only pull ellipsis with `ellipsis pull ellipsis`.
> Added option to only pull ellipsis

- src/path.bash
- test/path.bats
One of the functions I implemented for Ellipsis-TPM but is better placed in the shared code.
> Added path.expand function

- src/cli.bash
- src/ellipsis.bash
- src/fs.bash
- src/hooks.bash
- src/path.bash
- src/pkg.bash
- test/_helper.bash
- test/ellipsis.bats
- test/fs.bats
- test/path.bats
Adds a lot of quotes.
Even with all these quotes ellipsis isn't always properly working when there is a space in its path. To fix this we should change some logic here and there.
I already tested some logic changes but these will probably be for a future PR. (No logic changes in this PR)
> Fix unquoted paths/vars

- scripts/install.bash
Forgot to update the installer, not that smart of me!
> Fixed installer after init update

- src/cli.bash
- src/ellipsis.bash
- src/fs.bash
- src/git.bash
- src/hooks.bash
- src/registry.bash
- src/utils.bash
Seems like i forgot to change a few echo's.
Also fixes some more unquoted variables.
> Updated to msg functions where needed

- docs/api.md
- src/fs.bash
- test/fs.bats
Added `fs.link_rfile()` and tests.
Started on improved API documentation.
Fixes #19
> Link rfile

- src/msg.bash
- src/utils.bash
- test/utils.bats
Added utils.is_true to evaluate variables, nice to have when checking input and options.
Includes a test and I replaced alternatives in the code.
> utils.is_true

- src/cli.bash
I'll write a proper fix for this later.
> Temporary fix for quoting problem

- .gitignore
- README.md
- docs/api.md
- docs/hooks.md
- docs/init.md
- docs/install.md
- docs/usage.md
- mkdocs.yml
- src/env.sh
Fixed some bugs, improved speed (3x faster) and added documentation.
It should now also work on OSX without problems.
> Init improvements

- docs/hooks.md
- docs/pkgindex.md
> Update hook documentation

- docs/api.md
- src/git.bash
Just a few helpers i found useful when checking to see if i needed to git pull and run other update code.
> Added git.remote_branch, git.behind, git.is_behind

- docs/api.md
- docs/config.md
- mkdocs.yml
- src/cli.bash
- src/fs.bash
- test/cli.bats
- test/fs.bats
Fixes the cli.load_config function, and adds documentation.
> Fix config loading and add cli.load_config tests

- README.md
- docs/usage.md
- src/ellipsis.bash
- src/init.bash
- src/pkg.bash
- test/pkg.bats
As proposed in #77
Also added a few `pkg` test and updated a few functions to use `<<<` instead of an echo + pipe.
> Make it possible to customize package prefix

- src/env.sh
Replace grep test with remove + add logic to prevent duplicates.
Because this approach does not need any external functions it's about 4
to 5 times faster then the original implementation.
Also added some error logging in case the provided path is not a valid
directory.
> Optimize env_prepend/append_path functions

- src/env.sh
Improves env_init_pkg function speed with almost 30%.
fixes #91
> Optimize env_init_pkg function

- README.md
> Suggest using https for installing ellipsis

- src/pkg.bash
A very short PR which closes #103.
> Replace dependency on 'rev' with pure bash

- docs/api.md
- src/os.bash
> Add os.platform support for WSL1 and WSL2

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- Makefile
- docs/usage.md
- src/cli.bash
- src/ellipsis.bash
- src/env.sh
- src/fs.bash
- test/fs.bats
- test/init.bats
Hey, I feel ellipsis as my new $HOME framework, however it does not exactly fit to my needs. Before going further, let's try to improve some stuffs first.
This PR provides:
* Github actions support and Issue/PR templates
* Fixes some tests
* Fix BATS new URL
* Fix duplicate code test
* Some minor fixes in internal functions
* Better help message
As this PR:
* It's a quite a big PR, but it succeed tests. I hope this is acceptable.
* I'm not really sure how to implement tests on the new functions. Help welcome.
* I'm not really a professional developer, any workflow improvements or comments are welcome.
Ultimately I strongly believe in FOSS environment, I'd like to give back this work to the owner of this project, I hope this will be appreciated, however, If it's not welcome, I'm definitely …
> Various bugfixes and improvements
