README.md, scripts/install.bash, scripts/shim.sh
Updated all links to the new repository location. Before pulling this in, travis-ci should be activated for Ellipsis/ellipsis (will give build:invalid if not activated).
I also added a small part about the license to the readme.
=> Updated links to new repository location

bin/ellipsis
Allows bin/ellipsis to use the correct path to source init.bash when the
script is symlinked.
=> Make bin/ellipsis symlink aware

src/git.bash
If `git.clone` was used with a single argument an empty string was appended to the `git clone` command, which resulted in an error.
=> Fixed git.clone issue when using single argument

src/git.bash
Still don't get why it broke, it was exactly the same before the branch install update. (I've ran test locally first this time)
=> Fix git.clone problem when testing

src/ellipsis.bash
When the user is explicitly set in the ssh URL, an extra `@` is
introduced. To make sure this doesn't mess up branch detection,
`ssh://git@...` URL's are handled differently.
We could also support other users with more elaborate tests. But i think the need for that would be rather low.
=> Allow specifying git user in ssh URL's

src/hooks.bash
In `ellipsis.install` the link and install hooks are called. This makes it
unnecessary to call the link hook again in the install hook.
By removing the call from the install hook, the user can override
the hook without having to call the link hook manually.
=> Fixed double call to link hook

src/ellipsis.bash
Makes installing "official" extensions a lot easier.
It does make it impossible to install a package named `dot-ellipsis-package` with just `ellipsis-package` but I don't think anyone want's to do that. (and `username/ellipsis-package` still works as expected)
=> Allow short-hand notation for ellipsis extensions

test/ellipsis.bats, test/fs.bats
Ass mentioned in sstephenson/bats#49, tests written with `[[ ... ]]` should be followed by `|| false` to support older (< v4 ) bash versions.
Not a big issue but better avoid problems before they arise.
=> Fix tests for older bash versions

README.md, src/ellipsis.bash, src/fs.bash, src/hooks.bash, src/log.bash, src/msg.bash, src/pkg.bash, test/ellipsis.bats, test/fs.bats, test/log.bats, test/msg.bats, test/pkg.bats
Adds messaging functions used to show messages to the user and updates the log functions.
For Ellipsis-TPM I needed functions that could be overwritten to show all messages in Tmux copy mode. The `msg` functions do just that. They also make it possible to have more control over the output and make it possible to test colored and non colored output.
As the message functions show messages I updated the log functions to also log info to a file. I also added `log.fail` to make a distinction between an error that stops normal execution (fail) and an error that allows further actions (error).
In Ellipsis-TPM all actions that change something are logged. If everything goes well and nothing is altered a normal message is displayed. This makes it possible to keep track of changes over time with …
=> Msg and log functions

src/utils.bash
The function uses `$url` but if the URL is provided as first argument it was never assigned to this variable.
=> Fixed utils.run_installer when a URL is passed as $1

docs/api.md, src/extension.bash, src/utils.bash, test/extension.bats, test/utils.bats
Adds a `utils.version_compare` function and a file for extension related functions.
The first extension related function is `extension.is_compatible`, which checks if the ellipsis version is high enough. This should make it easy to deal with the changing Ellipsis API.
=> Added version comparison function(s)

test/_helper.bash, test/ellipsis.bats, test/fs.bats, test/pkg.bats
I disabled logging to the local logfile for all tests on the `_helper` level, so we don't accidentally pollute the local logfile in the future.
=> Make sure tests don't pollute local logs

bin/ellipsis, src/cli.bash
Since the introduction of the messaging functions it is no longer
necessary to strip color codes globally.
=> Remove global color stripping

bin/ellipsis, src/init.bash, test/_helper.bash
Updates the load function to load files provided by an extension if possible, else loads the Ellipsis version. This makes it possible to use the ellipsis init for extensions to.
Also adds the `ELLIPSIS_SRC` variable which contains the path to the Ellipsis src dir.
(and I also added some missing quotes)
=> Init extension support

src/ellipsis.bash
When installing a package, it would be more logical to call the `link` hook from the `install` hook. This is the case in the `uninstall` hook which calls the `unlink` hook.
It would be nice to have this consistent, but changing it now would brake a lot of `ellipsis.sh` files.
It is however preferred to call the `install` hook before the `link` hook. This should not cause trouble because linking and unlinking already works after installing a package.
The benefit of this change would be that we could compile/build files that would later be linked/unlinked.
=> Change install hook order

README.md, docs/hooks.md, docs/packages.md, src/ellipsis.bash, src/hooks.bash
Moved unlinking of the package from `hooks.uninstall` to `ellipsis.uninstall`. (As mentioned in #43 )
I also moved the deletion of the package as this shouldn't be overwritable.
Also adds some more documentation, and a little `README` fix.
=> Improve hook consistency

src/init.bash, src/log.bash, src/msg.bash, test/_helper.bash, test/bin.bats, test/cli.bats, test/log.bats, test/msg.bats
I updated the `msg` function to indent output based on nested runs. This functionality is meant to make output more clear when ellipsis or an ellipsis extension is used inside one of the hooks.
For example, in my tmux package the `update` hook runs `ellipsis-tpm update`. Without this indentation it is hard to see the difference between the output of ellipsis and ellipsis-tpm. I also run `ellipsis install ellipsis-tpm` from my install hook if ellipsis-tpm is not installed.
To keep the tests happy I had to split testing of the `cli` functions and `bin/ellipsis`. The `cli.bats` tests now run the `cli` functions directly and I added a separate `bin.bats` file for testing `bin/ellipsis`. This new test file also tests if symlinks are removed properly when finding `$ELLIPSIS_PATH`.
Adds …
=> Log and msg improvements

test/installer.bats
OSX needs specific order for command options.
=> Fixed installer tests for OSX

test/ellipsis.bats, test/pkg.bats, test/utils.bats
Made adding tests in ellipsis.bats less error prone by removing test-number based actions.
Added 'reason' for skipped tests.
=> Updated tests

README.md, docs/about.md
Google Code is no more. Updated the links to the resources on GitHub.
=> Fix broken links to Google Code

src/ellipsis.bash, test/ellipsis.bats
Fixes #50 (finally)
- Adds checks for ellipsis related, useless and sensitive files
- Ellipsis files are ignored
- Useless files are ignored with message, over-writable by explicit addition (single file)
- Sensitive files are added with warning
- `.` and `..` are ignored
- Includes tests
=> Fix upgrading

src/path.bash, test/path.bats
Now also expands '$HOME' and '$ELLIPSIS_HOME' strings.
=> Improved path.expand function

src/ellipsis.bash, src/env.sh, src/pkg.bash
This change makes it possible to check for dependencies in the install
hook for a package. If the hook returns a non zero exit status the
installation is aborted and logged as failed. Already downloaded files
are removed.
`ELLIPSIS_INIT` is now also exported so it's possible to check for the ellipsis init system as a dependency.
=> Add support for failing install hooks (dependency checks)

docs/hooks.md, docs/init.md, docs/packages.md, src/ellipsis.bash, src/pkg.bash
This was already available for extensions, but I think it's useful for packages too.
(optional and backwards compatible)
=> Auto check for ELLIPSIS_VERSION_DEP if defined

docs/hooks.md, src/cli.bash, src/ellipsis.bash, src/hooks.bash, src/utils.bash, test/ellipsis.bats, test/hooks.bats
Fixes #51 
Adds a new implementation for `ellipsis remove`, which now removes files from a package.
The requested safety for not accidentally trowing away uncommitted changes wil be added to the `uninstall` command in a future PR.
I also included a bugfix for `utils.prompt`, which complained about the return code not being numerical.
=> Fix add remove symmetry

docs/api.md, src/cli.bash, src/ellipsis.bash, src/git.bash, src/hooks.bash, src/utils.bash, test/utils.bats
Some small improvements that should make the `uninstall` command a lot safer.
Most notable change in the PR is the `ellipsis status` command now uses `git status -s` instead of `git diff --stat`.
The problem with diff stat is that it doesn't provide information about untracked files or uncommitted changes. The `uninstall` command would then prompt that there are changes, but `ellipsis status` would show none. For this reason I switched the nicer diff stat output for the more complete status output.
=> Improve uninstall safety

.travis.yml, docs/api.md, docs/usage.md, src/cli.bash, src/fs.bash, test/cli.bats, test/fs.bats
Adds config/rc file support. This will allow users to keep settings in there own config file.
Because we are just sourcing the file, it's also possible to hack-away and overwrite functions and do other fun stuff for more advanced users. Docs will follow once I have some more experience with the feature (as we did in the past).
I've also added an `info` command to do basic troubleshooting and for checking if ellipsis uses all correct settings.
The change in `.travis.yml` will hopefully work from the first time and auto check for both linux and osx. But I don't have much experience with this feature.
=> Ellipsis config

scripts/install.bash
`$ELLIPSIS_PACKAGES` was not set to the correct value during the
install. This made Ellipsis install the packages in the tmp install
directory.
The issue is fixed by setting the `$ELLIPSIS_PACKAGES` variable to its
correct value after installing Ellipsis itself.
Fixes #78
=> Fix quick install with packages

docs/api.md, src/fs.bash, test/fs.bats
Adds the `fs.link_rfiles` function to implement #80. Also reimplements
`fs.link_files` by calling `fs.link_rfiles` with an additional prefix
parameter.
`fs.link_files` now also has the option to specify an alternative folder
for linking the files. Default still links to `$ELLIPSIS_HOME`.
Includes additional tests for testing new features + docs.
=> Add fs.link_rfiles function

README.md, docs/install.md
Had a few questions about installing ellipsis without the installer (`curl | sh`) because this is not the best thing to do for security. So I added the example to the manual and README.
Also added a quick link to the init docs so people can more easily find the snippet to add to there bash/zsh rc file.
=> Add manual install example

src/fs.bash
When e.g. calling `ellipsis link <pkg>` where `<pkg>` implements a custom `pkg.link` hook that links files into subdirectories rather than directly into `$HOME`, the messages from `fs.backup` informing the user about removing the existing links were wrong.
E.g. the message said it was removing `~/mylink` instead of `~/.config/mylink`.
This change fixes these. (I have tested both broken symlinks as well as working symlinks and got the results I expected; for both files directly in `$HOME` as well as files in subdirectories.)
=> Show correct source during `fs.backup`

src/os.bash
Adds a more verbose `uname` command to fix detection of WSL2.
=> Fix WSL2 detection
